-- SQL Schema for OWASP 2026 Lab Users
CREATE TABLE IF NOT EXISTS `owasp_2026_users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(100) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
